// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1ldeWX-cRy-7Trx7nqloL79C9w9xl6s',
    appId: '1:341890753303:web:7404eba9c8b70f9e854d52',
    messagingSenderId: '341890753303',
    projectId: 'dailynest-35f52',
    authDomain: 'dailynest-35f52.firebaseapp.com',
    storageBucket: 'dailynest-35f52.firebasestorage.app',
    measurementId: 'G-V4BB8B5E5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoOpBYDd6VJ1_d4OVjAk21nI-zyRT2VJE',
    appId: '1:341890753303:android:fe556d9eed5134c4854d52',
    messagingSenderId: '341890753303',
    projectId: 'dailynest-35f52',
    storageBucket: 'dailynest-35f52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_l1rmS2ZEqtjVNwfl5y01_9oKrn7-Y_U',
    appId: '1:341890753303:ios:428026f2d3ed9ebe854d52',
    messagingSenderId: '341890753303',
    projectId: 'dailynest-35f52',
    storageBucket: 'dailynest-35f52.firebasestorage.app',
    iosBundleId: 'com.example.dailynest',
  );
}
